idf_component_register(SRCS 
                        "pong/pong_draw.c"
                        "pong/pong_engine.c"
                        "pong/pong_menu.c"
                        "pong/pong_menu_actions.c"
                        "periph/fs.c"
                        "periph/kb.c"
                        "periph/ble.c"
                        "periph/ble_server.c"
                        "periph/ble_client.c"
                        "periph/display.c"
                        "main.c"
                    INCLUDE_DIRS
                        "."
                    )