idf_component_register(SRCS 
                        "fs.c"
                        "display.c"
                        "pong/pong_draw.c"
                        "pong/pong_engine.c"
                        "pong/pong_menu.c"
                        "kb.c"
                        "main.c"
                    INCLUDE_DIRS
                        "."
                    )